# Generated by Django 5.0.3 on 2024-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_descricao_curso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
